export const GET_POKEMONS_SUCCESS = "GET_POKEMONS_SUCCESS";
export const GET_POKEMONS_REQUEST = "GET_POKEMONS_REQUEST";
export const GET_POKEMON_DATA_REQUEST = "GET_POKEMON_DATA_REQUEST";
export const GET_POKEMON_DATA_SUCCESS = "GET_POKEMON_DATA_SUCCESS";
export const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES";
export const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES";
export const TOGGLE_MENU = "TOGGLE_MENU";
